### ISSUE TITLE
How to start this script?

### ISSUE THREAD

**Issue by bsde1234** [Venryx/firebase-forum#1]
Can I do npm start?
Also is it possible to deploy it to firebase to make a forum website?

**Comment by Venryx** [comment]
The library is not yet ready for third-party use, unfortunately; it has too many "unmentioned dependencies" on components from my main project environment. (you can see the list of things it needs provided to it in: https://github.com/Venryx/firebase-forum/blob/master/Source/Manager.ts)

The good news is that I am currently updating several of my libraries from using Redux to MobX, and in the process, I am also working to make them "well modulized", where the API is realistically usable in other projects. (for example, it won't require passing in functions from a specific router library, a specific place to store user data, etc.)

Sorry for the delay; I didn't expect random people to be finding the library just from searches, so did not prepare the library for use in other projects from the start.

When the library is ready for third-party use, I will update the readme with usage instructions. (thus closing this issue)

**Comment by bsde1234** [comment]
Hi, any progress?

**Comment by Venryx** [comment]
Not really, no; it's not a high priority at the moment, due to the bare-bones nature of the library currently + more importantly, the fact that it is enmeshed with other libraries of mine right now.

Perhaps this could work as an alternative: https://github.com/hoppula/refire-forum
